apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - name: guestbook-ui
          image: rafi1945/fastapi-argocd-app:b78734f81fcdda3c73e8af41f4928a48a338030e
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://host.docker.internal:5000"
            - name: MODEL_URI
              value: "models:/IrisClassifier/1"